#!/usr/bin/env bash
# i18n-extract.sh - extract every translatable English string from the
# sources and print a language file template (see docs/I18N.md).
#
#   tools/i18n-extract.sh > lang/TEMPLATE.sh
#   tools/i18n-extract.sh lang/fr.sh > lang/fr.sh.new   # merge existing translations
#
# Empty translations fall back to English at run time, so a partially
# translated file is always usable.
set -o pipefail
PVETTY_HOME=$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/.." && pwd)
existing=${1:-}

perl - "$existing" "$PVETTY_HOME"/pvetty "$PVETTY_HOME"/lib/*.sh "$PVETTY_HOME"/views/*.sh <<'PERL'
use strict;
use warnings;

my $existing = shift @ARGV;
my %str;
my %old;
my ($lang_name, $date_fmt, $date_short) = ('Language name', '%Y-%m-%d %H:%M:%S', '%b %d %H:%M:%S');

# Existing translations (to merge).
if ($existing && -r $existing) {
    open(my $fh, '<', $existing) or die;
    while (<$fh>) {
        $old{$1} = $2 if /^\s*\["((?:[^"\\]|\\.)*)"\]="((?:[^"\\]|\\.)*)"/;
        $lang_name = $1 if /^LANG_NAME="([^"]*)"/;
        $date_fmt = $1 if /^DATE_FMT='([^']*)'/;
        $date_short = $1 if /^DATE_SHORT='([^']*)'/;
    }
}

sub add {
    my $s = shift;
    return if !defined $s || length($s) < 2 || $s =~ /^[\$\s]/ || $s !~ /[A-Za-z]/;
    # Technical strings: variables, paths, URLs, internal names, key names.
    return if $s =~ /\$|^\/\w|\/\?|^choice[_ ]|^[a-z]+(?:_[a-z]+)+$|^F\d+(?: \S)?$|^[a-z] F\d+$|^[0-9A-F]{2}(?::[0-9A-F]{2})+$|^(?:ge|le)$/;
    $str{$s} = 1;
}
# Key hints "k:Label k:Label_with_spaces": the labels are translated one by one.
sub hint_like { my $s = shift; my @t = split ' ', $s; return @t && !grep { !m{^[^:|\s]{1,8}:[^:|\s]+$} } @t }

my $q = qr/"((?:[^"\\\$]|\\.)*)"/;   # double quoted literal without expansions
for my $file (@ARGV) {
    open(my $fh, '<', $file) or next;
    while (my $l = <$fh>) {
        next if $l =~ /^\s*#/;
        # Key hints first (VIEW_HINT, GRID_HINT, crud extra=...), then removed
        # from the line so that the other patterns do not see their pieces.
        while ($l =~ /"((?:[^"\\\$]|\\.)*)"/g) {
            my $h = $1;
            next unless hint_like($h);
            for my $t (split ' ', $h) { my ($k, $lab) = split /:/, $t, 2; $lab =~ tr/_/ /; add($lab) }
        }
        $l =~ s/"((?:[^"\\\$]|\\.)*)"/hint_like($1) ? '""' : "\"$1\""/ge;
        $l =~ s/\b(extra|hint)="([^"]*)"/ do { my $h = $2; if (hint_like($h)) { for my $t (split ' ', $h) { my ($k, $lab) = split m{:}, $t, 2; $lab =~ tr{_}{ }; add($lab) } } "$1=\"\"" } /ge;
        # T "..." / Tf "..."
        add($1) while $l =~ /\bTf? $q/g;
        # helpers whose first (or second) argument is a source string
        add($1) while $l =~ /\b(?:c_section|c_kv|c_kv_sel|cfg_line|usage_line|menu_add \S+|tb_add \S+|c_msg \S+|dlg_(?:yesno|input|password|msg|textbox|menu|checklist)) $q/g;
        add($1) while $l =~ /\bDLG_(?:OK|CANCEL)_LABEL=$q/g;
        add($1) while $l =~ /\bdlg_(?:yesno|input|password|msg|menu|checklist) "[^"]*" $q/g;
        # view_menu entries "id|Label|icon|level"
        add($1) while $l =~ /"[\w-]+\|([^|"]+)\|[\w-]*\|\d"/g;
        # table specs "field:Header:width..." separated by |
        while ($l =~ /(?:view_table|table_spec)\b[^"]*(?:"[^"]*"\s+){0,2}"([^"]*:[^"]*)"/g) {
            for my $col (split /\|/, $1) {
                my (undef, $h) = split /:/, $col;
                add($h);
            }
        }
        # Associative tables of display strings: [key]="Display"
        add($1) while $file !~ /i18n\.sh$/ && $l =~ /\[[\w-]+\]="([^"\$]+)"/g;
        # fw_options entries "key:Label:Default[:bool]"
        while ($l =~ /"[\w-]+:([^:"]+):([^:"]+)(?::bool)?"/g) { add($1); add($2) }
    }
}

print <<"HEAD";
# shellcheck shell=bash
# pvetty translation file - generated by tools/i18n-extract.sh
# Copy to lang/<code>.sh (e.g. lang/fr.sh), set LANG_NAME and fill the
# translations. Empty entries fall back to English. Keep printf
# placeholders (%s, %d) in the same order.
LANG_NAME="$lang_name"
DATE_FMT='$date_fmt'
DATE_SHORT='$date_short'
L=(
HEAD
for my $s (sort { lc($a) cmp lc($b) or $a cmp $b } keys %str) {
    my $t = $old{$s} // '';
    printf "    [\"%s\"]=\"%s\"\n", $s, $t;
}
print ")\n";
PERL
