#!/usr/bin/env bash
# i18n-extract.sh - extract every translatable English string from the
# sources and print a language file template (see docs/I18N.md).
#
#   tools/i18n-extract.sh > lang/TEMPLATE.sh
#   tools/i18n-extract.sh lang/fr.sh > lang/fr.sh.new   # merge existing translations
#
# Empty translations fall back to English at run time, so a partially
# translated file is always usable.
set -o pipefail
PVETTY_HOME=$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/.." && pwd)
existing=${1:-}

perl - "$existing" "$PVETTY_HOME"/pvetty "$PVETTY_HOME"/lib/*.sh "$PVETTY_HOME"/views/*.sh <<'PERL'
use strict;
use warnings;

my $existing = shift @ARGV;
my %str;
my %old;
my ($lang_name, $date_fmt, $date_short) = ('Language name', '%Y-%m-%d %H:%M:%S', '%b %d %H:%M:%S');

# Existing translations (to merge).
if ($existing && -r $existing) {
    open(my $fh, '<', $existing) or die;
    while (<$fh>) {
        $old{$1} = $2 if /^\s*\["((?:[^"\\]|\\.)*)"\]="((?:[^"\\]|\\.)*)"/;
        $lang_name = $1 if /^LANG_NAME="([^"]*)"/;
        $date_fmt = $1 if /^DATE_FMT='([^']*)'/;
        $date_short = $1 if /^DATE_SHORT='([^']*)'/;
    }
}

sub add { my $s = shift; return if !defined $s || length($s) < 2 || $s =~ /^[\$\s]/ || $s !~ /[A-Za-z]/; $str{$s} = 1 }

my $q = qr/"((?:[^"\\\$]|\\.)*)"/;   # double quoted literal without expansions
for my $file (@ARGV) {
    open(my $fh, '<', $file) or next;
    while (my $l = <$fh>) {
        next if $l =~ /^\s*#/;
        # T "..." / Tf "..."
        add($1) while $l =~ /\bTf? $q/g;
        # helpers whose first (or second) argument is a source string
        add($1) while $l =~ /\b(?:c_section|c_kv|c_kv_sel|cfg_line|usage_line|menu_add \S+|tb_add \S+|c_msg \S+|dlg_(?:yesno|input|password|msg|textbox|menu)) $q/g;
        add($1) while $l =~ /\bdlg_(?:yesno|input|password|msg|menu) "[^"]*" $q/g;
        # view_menu entries "id|Label|icon|level"
        add($1) while $l =~ /"[\w-]+\|([^|"]+)\|[\w-]*\|\d"/g;
        # table specs "field:Header:width..." separated by |
        while ($l =~ /(?:view_table|table_spec)\b[^"]*(?:"[^"]*"\s+){0,2}"([^"]*:[^"]*)"/g) {
            for my $col (split /\|/, $1) {
                my (undef, $h) = split /:/, $col;
                add($h);
            }
        }
        # Associative tables of display strings: [key]="Display"
        add($1) while $l =~ /\[[\w-]+\]="([^"\$]+)"/g;
        # fw_options entries "key:Label:Default[:bool]"
        while ($l =~ /"[\w-]+:([^:"]+):([^:"]+)(?::bool)?"/g) { add($1); add($2) }
    }
}

print <<"HEAD";
# shellcheck shell=bash
# pvetty translation file - generated by tools/i18n-extract.sh
# Copy to lang/<code>.sh (e.g. lang/fr.sh), set LANG_NAME and fill the
# translations. Empty entries fall back to English. Keep printf
# placeholders (%s, %d) in the same order.
LANG_NAME="$lang_name"
DATE_FMT='$date_fmt'
DATE_SHORT='$date_short'
L=(
HEAD
for my $s (sort { lc($a) cmp lc($b) or $a cmp $b } keys %str) {
    my $t = $old{$s} // '';
    printf "    [\"%s\"]=\"%s\"\n", $s, $t;
}
print ")\n";
PERL
